version: '3.8'

services:
  receipt-scanner:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - PAGE_ID=${PAGE_ID}
      - RATE_LIMIT_PER_MINUTE=10
      - MAX_FILE_SIZE_MB=10
      - CORS_ORIGINS=${CORS_ORIGINS:-}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs 